#!/usr/bin/env node
var fs = require('fs')

var dirName = process.argv[2]
process.chdir("/JavaScriptworks/jirengu")
if(!fs.existsSync(dirName)){
  fs.mkdirSync(dirName)
  process.chdir(dirName)
  fs.mkdirSync('test')
  fs.mkdirSync('homework')
  fs.mkdirSync('JavaScript')
  fs.writeFileSync("index.html","")
  process.chdir('JavaScript')
  fs.mkdirSync('images')
  fs.mkdirSync('scripts')
  fs.mkdirSync('styles')
  fs.writeFileSync("index.html","")
  fs.writeFileSync("scripts/main.js","")
  fs.writeFileSync("styles/layout.css","")
  console.log('success')
}
else{
  console.log('error: dirName exists')
}
process.exit(0)